config/routes.rb
H4F::Application.routes.draw do
  resources :stays


  resources :bookings


  resources :groups


  resources :people


  resources :rooms
    
  resources :hotels


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/person.rb
class Person < ActiveRecord::Base
    belongs_to :group, inverse_of: :people
    has_many :bookings, inverse_of: :person
    has_many :stays, inverse_of: :person
  attr_accessible :ableToShareRoom, :age, :email, :group_id, :imie, :mobile, :nazwisko, :role
  
  def full_name
      "#{imie} #{nazwisko}"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
     before_filter :authenticate_user!
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
  
  
  
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= simple_form_for(@person) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :imie %>
    <%= f.input :nazwisko %>
    <%= f.input :role %>
    <%= f.label "Grupa" %>
    <%= f.select :group_id , Group.all.map { |group| [group.name, group.id] } %>
    <%= f.input :age %>
    <%= f.label "able To Share Room" %>
    <%= f.select(:ableToShareRoom, options_for_select([['No', 0], ['Yes', 1]], @person.ableToShareRoom)) %>
    <%= f.input :mobile %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Imie</th>
    <th>Nazwisko</th>
    <th>Role</th>
    <th>Group</th>
    <th>Age</th>
    <th>Able to share room</th>
    <th>Mobile</th>
    <th>Email</th>
<th>Bookings</th>
    <th></th>

  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.imie %></td>
    <td><%= person.nazwisko %></td>
    <td><%= person.role %></td>
    <td><%= person.group_id %></td>
    <td><%= person.age %></td>
    <td><%= person.ableToShareRoom %></td>
    <td><%= person.mobile %></td>
    <td><%= person.email %></td>
    <td><%= person.bookings.count %></td>
    <td><%= link_to 'Show', person %>
    <%= link_to 'Edit', edit_person_path(person) %>
    <%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<div>
<p>
  <b>Imie:</b>
  <%= @person.imie %>
</p>

<p>
  <b>Nazwisko:</b>
  <%= @person.nazwisko %>
</p>

<p>
  <b>Role:</b>
  <%= @person.role %>
</p>

<p>
  <b>Group:</b>
  <%= @person.group_id %>
</p>


<p>
  <b>Age:</b>
  <%= @person.age %>
</p>

<p>
  <b>Able to share room:</b>
  <%= @person.ableToShareRoom %>
<% if @person.ableToShareRoom==0  %>
    <b>No</b>
<% else %>
    <b>Yes</b>
</p>

<% end %>
<p>
  <b>Mobile:</b>
  <%= @person.mobile %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>
</div>
<div>
<table>
<tr>
<th>Check in</th>
<th>Check out</th>
<th></th>

</tr>

<% @person.stays.each do |stay| %>
<tr>
<td><%= stay.check_in %></td>
<td><%= stay.check_out %></td>
<td><%= link_to 'Show', stay %>
<%= link_to 'Edit', edit_stay_path(stay) %>
<%= link_to 'Destroy', stay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</table>
</div>
<div>
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %> |
<%= link_to 'New Stay', new_stay_path(:new_stays_for_person => @person.id) %>
</div>