config/routes.rb
H4F::Application.routes.draw do
  resources :stays


  resources :bookings


  resources :groups


  resources :people


  resources :rooms
    
  resources :hotels


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :people, inverse_of: :group
    has_many :bookings, inverse_of: :group
    has_many :stays, inverse_of: :group
  attr_accessible :menager, :name
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_filter :authenticate_user!
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new
      @group.people.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :menager %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Menager</th>
    <th>Members</th>
    <th>Bookings</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.menager %></td>
    <td><%= group.people.count %></td>
    <td><%= group.bookings ? group.bookings.count : group.people.bookings.count %></td>
<% counter = 0 %>
<%  group.people.each do |person| %>
<%  counter = counter + person.bookings.count %>
<% end %>
    <td><%= counter %>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>

<p>
  <b>Menager:</b>
  <%= @group.menager %>
</p>

<table>
<tr>
<th>Imie</th>
<th>Nazwisko</th>
<th>Role</th>
<th>Able to share room</th>
<th>Mobile</th>
<th>Email</th>
<th>Bookings</th>
<th></th>

</tr>

<% @group.people.each do |person| %>
<tr>
<td><%= person.imie %></td>
<td><%= person.nazwisko %></td>
<td><%= person.role %></td>
<td><%= person.ableToShareRoom %></td>
<td><%= person.mobile %></td>
<td><%= person.email %></td>
<td><%= person.bookings.count %></td>
<td><%= link_to 'Show', person %>
<%= link_to 'Edit', edit_person_path(person) %>
<%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</table>



<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %> |
<%= link_to 'Add a person', new_person_path %> |
<%= link_to 'New Stay', new_stay_path(:new_stays_for_group => @group.id) %>