config/routes.rb
H4F::Application.routes.draw do
  resources :stays


  resources :bookings


  resources :groups


  resources :people


  resources :rooms
    
  resources :hotels


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
    has_many :rooms, inverse_of: :hotel, dependent: :destroy
    has_many :bookings, inverse_of: :hotel, dependent: :destroy
    attr_accessible :city, :geolocation, :name, :postcode, :street, :picture
    mount_uploader :picture, PictureUploader
    
    def free_rooms
        rooms.joins(:bookings).where('bookings.room_id = rooms.id').count
    end
    
    
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
    before_filter :authenticate_user!
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])
     
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.json
  def new
    @hotel = Hotel.new
       @hotel.rooms.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(params[:hotel])

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render json: @hotel, status: :created, location: @hotel }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.json
  def update
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= simple_form_for(@hotel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :postcode %>
    <%= f.input :geolocation %>
    <%= f.file_field :picture %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %> |

<%= link_to 'Add a Room', new_room_path %>

app/views/hotels/index.html.erb
<h3>Listing hotels</h3>
<div class="span8">
<table class="table table-condensed">
<thead>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Street</th>
    <th>City</th>
    <th>Postcode</th>
    <th>Geolocation</th>
    <th>Rooms</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
 <tbody>
<% @hotels.each do |hotel| %>
  <tr>
    <td><%= image_tag(hotel.picture_url, :width => 60) if hotel.picture.present? %></td>
    <td><%= hotel.name %></td>
    <td><%= hotel.street %></td>
    <td><%= hotel.city %></td>
    <td><%= hotel.postcode %></td>
    <td><%= hotel.geolocation %></td>
    <td><%= hotel.rooms.size %></td>
    <td><%= hotel.free_rooms %></td>
    <td><%= link_to 'Show', hotel %></td>
    <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
    <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Hotel', new_hotel_path %>
</div>
<br />

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>
<div>
<%= image_tag(@hotel.picture_url, :width => 600) if @hotel.picture.present? %>
</div>
<p>
  <b>Name:</b>
  <%= @hotel.name %>
</p>

<p>
  <b>Street:</b>
  <%= @hotel.street %>
</p>

<p>
  <b>City:</b>
  <%= @hotel.city %>
</p>

<p>
  <b>Postcode:</b>
  <%= @hotel.postcode %>
</p>

<p>
  <b>Geolocation:</b>
  <%= @hotel.geolocation %>
</p>

<table>
<tr>
<th>Beds</th>
<th>Room type</th>
<th>Room number</th>
<th></th>
<th></th>
<th></th>
</tr>

<% @hotel.rooms.each do |room| %>
<tr>
<td><%= room.beds %></td>
<td><%= room.roomtype %></td>
<td><%= room.roomNumber %></td>
<td><%= link_to 'Show', room %></td>
<td><%= link_to 'Edit', edit_room_path(room) %></td>
<td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</table>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %> |
<%= link_to 'Add a Room', new_room_path %>